Check for success status of ffmpeg commands

diff --git a/mimic b/mimic
--- a/mimic
+++ b/mimic
@@ -48,14 +48,28 @@ posX=0
 posY=$((${heightStep} * 11))
 
 # Draw using ffmpeg
-ffmpeg -y -i ${input} -vf "drawbox=x=${posX}:y=${posY}:w=${width}:h=${heightStep}:color=black@0.5:t=max" -qscale 0 ${tempdir}/${inputBase} &>/dev/null
+output=$(ffmpeg -y -i ${input} -vf "drawbox=x=${posX}:y=${posY}:w=${width}:h=${heightStep}:color=black@0.5:t=max" -qscale 0 ${tempdir}/${inputBase} 2>&1)
+
+# Check for success
+if [[ $? != 0 ]]; then
+  echo "Error: couldn't draw translucent box"
+  printf -- "---DEBUG START---\n%s\n---DEBUG STOP---\n" "$output"
+  exit 1
+fi
 
 # Position for the text
 posX="$((${width} / 2))-(text_w/2)"
 posY="$((${heightStep} * 11 + ${heightStep} / 2 ))-(text_h/2)"
 
 # Draw using ffmpeg
-ffmpeg -y -i ${tempdir}/${inputBase} -vf drawtext="fontfile=/System/Library/Fonts/Helvetica.dfont:text='${text}':fontsize=70:fontcolor=white:x=${posX}:y=${posY}" ${inputPath}/new_${inputBase} &>/dev/null
+output=$(ffmpeg -y -i ${tempdir}/${inputBase} -vf drawtext="fontfile=/System/Library/Fonts/Helvetica.dfont:text='${text}':fontsize=70:fontcolor=white:x=${posX}:y=${posY}" ${inputPath}/new_${inputBase} 2>&1)
+
+# Check for success
+if [[ $? != 0 ]]; then
+  echo "Error: couldn't draw text"
+  printf -- "---DEBUG START---\n%s\n---DEBUG STOP---\n" "$output"
+  exit 1
+fi
 
 # Remove tempfile
 rm -rf ${tempdir}
